[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Runtime.InteropServices.Guid("1733a48d-854c-437b-826f-6f67b1faa069")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyTitle("Ecdev.Weixin.MP")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 2012 - 2015 Ecdev. All Rights Reserved.")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.DisableOptimizations | System.Diagnostics.DebuggableAttribute.DebuggingModes.EnableEditAndContinue | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | System.Diagnostics.DebuggableAttribute.DebuggingModes.Default)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("深圳市惠众云商科技有限公司")]
[assembly: System.Reflection.AssemblyProduct("Ecdev.Weixin.MP")]

