[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyDescription("Release")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("2fbbce7a-9f9f-4953-ac19-d373c976df86")]
[assembly: System.Reflection.AssemblyProduct("Ecdev")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
//[assembly: System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName=".NET Framework 4")]
[assembly: System.Reflection.AssemblyTitle("EcShop.UI.Common.Controls")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0")]
[assembly: System.Web.UI.WebResource("region.helper.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("ImageUploader.script.upload.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("ImageUploader.css.style.css", "text/css")]
[assembly: System.Web.UI.WebResource("ImageUploader.images.upload.png", "image/png")]
[assembly: System.Reflection.AssemblyCompany("深圳市惠众云商科技有限公司")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 2012 - 2015 Ecdev.cn. All Rights Reserved.")]

