[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("5383c3f3-78d8-4904-8047-9a576b386447")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
////[assembly: System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName=".NET Framework 4")]
[assembly: System.Reflection.AssemblyTitle("UI.Common.Validator")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0")]
[assembly: System.Reflection.AssemblyCompany("深圳市惠众云商科技有限公司")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 2012 - 2015 Ecdev.cn. All Rights Reserved.")]
[assembly: System.Reflection.AssemblyProduct("Ecdev")]
[assembly: System.Reflection.AssemblyDescription("Release")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]

