[assembly: System.Reflection.AssemblyVersion("2.1.5459.27928")]
//[assembly: System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName=".NET Framework 4")]
[assembly: System.Reflection.AssemblyTitle("SqlCommonDataProvider")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("7d958727-9aae-46a0-abbd-08757b1026b2")]
[assembly: System.Reflection.AssemblyCompany("深圳市惠众云商科技有限公司")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 2012 - 2015 Ecdev.cn. All Rights Reserved.")]
[assembly: System.Reflection.AssemblyProduct("Ecdev")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyDescription("Release")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]

