[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.DisableOptimizations | System.Diagnostics.DebuggableAttribute.DebuggingModes.EnableEditAndContinue | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | System.Diagnostics.DebuggableAttribute.DebuggingModes.Default)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Web.UI.WebResource("Ecdev.Plugins.Controls.plugin.js", "text/javascript")]
[assembly: System.Reflection.AssemblyCompany("深圳市惠众云商科技有限公司")]
[assembly: System.Reflection.AssemblyProduct("PluginManager")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyTitle("PluginManager")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyDescription("Debug")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 2012 - 2015 Ecdev. All Rights Reserved.")]
[assembly: System.Runtime.InteropServices.Guid("5aa460b0-9af8-4994-b067-1460364adfc6")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0")]

