[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Runtime.InteropServices.Guid("f2e4cfb0-174e-4aef-a4ee-f75c16ddd0ee")]
[assembly: System.Reflection.AssemblyCompany("深圳市惠众云商科技有限公司")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 2012 - 2015 Ecdev.cn. All Rights Reserved.")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyDescription("Release")]
[assembly: System.Reflection.AssemblyProduct("Ecdev")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
//[assembly: System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName=".NET Framework 4")]
[assembly: System.Reflection.AssemblyTitle("Web")]
[assembly: log4net.Config.XmlConfigurator(ConfigFile = "log4net.config", Watch = true)]
