using System;
namespace EcShop.Entities.Store
{
	public enum Privilege
	{
        PCTopicManager,
        ReferralRequest,
        Referrals,
        SupplierHotProduct,
        NewVouchers,
        UsedVouchers,
        UsedCoupons,
        AppRunImgInfo,
        ManageAppRecommendSupplier,
        ManageAppHotSupplier,
        ManageAppIcon,
        SplittinDrawRequest,
        ManageAppHotProduct,
        Appmanagehotkeywords,
        ManageAppNewProduct,
        ManageAppCheapProduct,
        splittindrawrecord,
        ManageAppNavigate,
        SupplierSelectCategory,
        BrandType,
		Summary = 1000,
		SiteSettings,
		EmailSettings,
		SMSSettings,
		PaymentModes,
		ShippingModes,
		ShippingTemplets,
		ExpressComputerpes,
		MessageTemplets,
		PictureMange,
		Themes = 2001,
		Affiches,
		HelpCategories,
		Helps,
		ArticleCategories,
		Articles,
		FriendlyLinks,
		HotKeywords,
		Votes,
		Products = 3001,
		AddProducts,
		EditProducts,
		DeleteProducts,
		InStockProduct,
		UpShelfProducts,
		OffShelfProducts,
        ProductFractionChange,
		ProductUnclassified = 3010,
		SubjectProducts,
		ProductBatchUpload,
		ProductTypes = 3017,
		AddProductType,
		EditProductType,
		DeleteProductType,
		ProductCategory,
		AddProductCategory,
		EditProductCategory,
		DeleteProductCategory,
		BrandCategories,
		ProductBatchExport,
		TopicManager,
		TopicAdd,
		TopicEdit,
		TopicDelete,
        ImportSourceTypeManager,
        ImportSourceTypeView,
        ImportSourceTypeAdd,
        ImportSourceTypeEdit,
        ImportSourceTypeDelete,
		Orders = 4001,
		DeleteOrder,
		EditOrders,
		CofimOrderPay,
		OrderSendGoods,
		ExpressPrint,
		RefundOrder,
		RemarkOrder,
		ExpressTemplates,
        Shippers = 4010,
		OrderLookup,
		OrderRefundApply,
		OrderReplaceApply,
		OrderReturnsApply,
        OrderRefundApplyView = 4015,
        OrderRefundApplyDelete,
        OrderRefundApplyAccept,
        OrderRefundApplyRefuse,
        OrderRefundApplySelExcel,
        OrderRefundApplyTimeExcel = 4020,
        OrderReplaceApplyView,
        OrderReplaceApplyDelete,
        OrderReplaceApplyAccept,
        OrderReplaceApplyRefuse,
        OrderReplaceApplySelExcel = 4025,
        OrderReplaceApplyTimeExcel,
        OrderReturnsApplyView,
        OrderReturnsApplyDelete,
        OrderReturnsApplyAccept,
        OrderReturnsApplyRefuse = 4030,
        OrderReturnsApplySelExcel,
        OrderReturnsApplyTimeExcel = 4032,
        RefundOrderManager,
        RefundOrderView,
        RefundOrderDelete,
        RefundOrderExcel,
        ReturnOrder,
        ReturnOrderView,
        ReturnOrderDelete,
        ReturnOrderExcel,
		Members = 5001,
		EditMember,
		DeleteMember,
		MemberGrades,
		AddMemberGrade,
		EditMemberGrade,
		DeleteMemberGrade,
		OpenIdServices,
		OpenIdSettings,
		MemberBalanceStatistics,
		MemberDrawRequestStatistics,
		VServerConfig = 6001,
		AppConfig,
		ManageMenu,
		VIPcard,
		AddReplyOnKey,
		EditReplyOnkey,
		DeleteCustomeReply,
		ManageMaterial,
		TopicList,
		ManageVThemes,
		SetVThemes,
		ManageLotteryActivity,
		ManageActivity,
		ManageLotteryTicket,
		AddArticle,
		EditArticle,
		DeleteArticle,
		vBannerManage,
		vBannerAdd,
		vBannerEdit,
		vBannerDelete,
		vIconSet,
		vProductSet,
		AddActivity,
		EditActivity,
		DeleteActivity,
		AddLotteryActivity,
		EditLotteryActivity,
		DeleteLotteryActivity,
		AddLotteryTicket,
		EditLotteryTicket,
		DeleteLotteryTicket,
		AddMenu,
		EditMenu,
		DeleteMenu,
		VpayConfig,
		vMobileAlipaySet,
        vIsViewEdit,
		vShengPaySet = 6039,
		vOfflinePaySet,
		CustomeReplyManager,
		MutiArticleAdd,
		MutiArticleEdit,
		ProductConsultationsManage = 7001,
		ProductReviewsManage,
		ReceivedMessages,
		SendedMessages,
		AddMessage,
		ManageLeaveComments,
		ClientGroup,
		ClientNew,
		ClientActivy,
		ClientSleep,
		Gifts = 8001,
		ProductPromotion,
        SearchPromotionPresentPro,
        SearchPromotionProduct,
		OrderPromotion,
		BindProduct,
		GroupBuy,
		CountDown,
		Coupons,
		MemberAccount = 9001,
		MemberReCharge,
		BalanceDrawRequest,
		SaleReport = 10001,
		OrderStatistics,
		SaleDetails,
        SaleStoreDetails,
		SaleTargets,
		ProductSaleRanking,
		ProductSaleStatistics,
		MemberRanking,
		MemberArealDistributionStatistics,
		UserIncreaseStatistics,
        ServiceStatistics,
        SuppliersSalesView,
        SuppliersSalesExcel,
        SuppliersSales,
		WapManageThemes = 11001,
		WapThemesSet,
		WapBannerManage,
		WapBannerAdd,
		WapBannerEdit,
		WapBannerDelete,
		WapIconSet,
		WapProductSet,
		WapHomeTopicSet,
		WapMobileAlipaySet,
		WapShengPaySet,
		WapOfflinePaySet,
		AliohManageThemes = 12001,
		AliohThemesSet,
		AliohBannerManage,
		AliohBannerAdd,
		AliohBannerEdit,
		AliohBannerDelete,
		AliohIconSet,
		AliohProductSet,
		AliohHomeTopicSet,
		AliohMobileAlipaySet,
		AliohShengPaySet,
		AliohOfflinePaySet,
		AliohBaseConfig,
		AliohManageMenu,
		AliohAddMenu,
		AliohEditMenu,
		AliohDeleteMenu,
		AppADImageSet = 13001,
		AppAdImageAdd,
		AppAdImageEdit,
		AppAdImageDelete,
		AppProductSet,
		AndroidUP,
		IOSUP,
		AppMobileAlipaySet,
		AppShengPaySet,
        AppTFTPaySet,
        AppOfflinePaySet = 13010,
		AppHomeTopicSet,
        Supplier,
        SupplierView,
        SupplierAdd,
        SupplierEdit = 13015,
        SupplierDelete,
        ReconciliationOrders,
        ReconciOrdersView,
        ReconciOrdersExcel,
        ReconciOrdersDetailsView = 13020,
        ReconciOrdersDetailsExcel,
        ReconciliationOrdersDetailed,
        AggregatePayable,
        SitesManager,
        Sites = 13025,
        SitesView,
        SitesAdd,
        SitesEdit,
        SitesDelete,
        TaxRateManager = 13030,
        TaxRateView,
        TaxRateAdd,
        TaxRateEdit,
        TaxRateDelete,
        StoreManager = 13035,
        Store,
        StoreView,
        StoreAdd,
        StoreEdit,
        StoreDelete = 13040,
        StoreRelatedProduct,
        StoreOrderView,
        StoreOrderDelete,
        StoreOrderClose,
        StoreOrderSend = 13045,
        StoreOrderPrintPosts,
        StoreOrderPrintGoods,
        StoreOrderDown,
        StoreOrderDownSelExcel,
        StoreOrderDownTimeExcel = 13050,
        StoreOrderDownGoodsPick,
        StoreOrderClear,
        StoreOrderClearSelExcel,
        StoreOrderClearTimeExcel,
        StoreOrderClearGoodsPick = 13055,
        StoreOrderBatchSend,
        StoreOrderUploadGoods,
        StoreOrderReplaceAccept,
        StoreOrderReplaceRefuse,
        StoreOrderReturnAccept = 13060,
        StoreOrderReturnRefuse,
        StoreOrderRefundAccept,
        StoreOrderRefundRefuse,
        CustomServiceView,
        CustomServiceCreateReport = 13065,
        StoreOrder,
        CustomService,
        ProductSaleAsBrand = 14000,
        ProductSaleAsBrandView,
        ProductSaleAsBrandExcel,
        ProductSaleAsImportSource,
        ProductSaleAsImportSourceView,
        ProductSaleAsImportSourceExcel,
        Vouchers,
        StoreOrderAdd = 15000,
        SkusSelect,
        ShipAddressSelect,
        StoreAddManager,
        SupplierAddManager,
        SupplierManage = 15005,
        SupplierOrder,
        SupplierOrderView,
        SupplierOrderAdd,
        SupplierOrderDelete,
        SupplierOrderClose = 15010,
        SupplierOrderSend,
        SupplierOrderReplaceAccept,
        SupplierOrderReplaceRefuse,
        SupplierOrderReturnAccept,
        SupplierOrderReturnRefuse = 15015,
        SupplierOrderRefundAccept,
        SupplierOrderRefundRefuse,
        SupplierOrderPrintPosts,
        SupplierOrderPrintGoods,
        SupplierOrderBatchSend = 15020,
        SupplierOrderUploadGoods,
        SupplierOrderDown,
        SupplierOrderDownSelExcel,
        SupplierOrderDownTimeExcel,
        SupplierOrderDownGoodsPick = 15025,
        SupplierOrderClear,
        SupplierOrderClearSelExcel,
        SupplierOrderClearTimeExcel,
        SupplierOrderClearGoodsPick,
        SupplierProductManage = 15030,
        SupplierProductView,
        SupplierProductAdd,
        SupplierProductEdit,
        SupplierProductDelete,
        SupplierProductInStock = 15035,
        SupplierProductUp,
        SupplierProductDown,
        SupplierOrderRemark,
        AppWxPaySet,
        AppRunImg,
        SetDefaultAddress,
        WxPayQrCodeSet,
        Editethems,     
        SupplierProductPromotions,
        SupplierOrderPromotions,
        SupplierBundlingProducts,
        SupplierGroupBuys,
        SupplierCountDowns = 15045,
        Supplierindex,
        SupplierManageBanner,
        SupplierManageNavigate,
        SupplierHomeProductSetting,
        SupplierHomeTopicSetting = 15050,
        SupplierManageVHotProduct,
        SupplierManageNewProduct,
        SupplierManageCheapProduct,
        SupplierVshopmanagehotkeywords,
        SupplierManageAppBanner=15055,
        SupplierManageAppNavigate,
        SupplierAppProductSetting,
        SupplierAppHomeTopicSetting,
        SupplierManageAppHotProduct,
        SupplierManageAppNewProduct=15060,
        SupplierManageAppCheapProduct,
        SupplierAppmanagehotkeywords,
        UnitsManager=15063,
        UnitsView,
        UnitsAdd,
        UnitsEdit,
        UnitsDelete,

        //PC端轮播图
        SupplierPCBanner=15070,
        EditMySupplierInfo,

        //供应商专题配置
        SupplierTopicList=15072,
        AddSupplierTopic,
        SetSupplierTopicProducts,
        SearchSupplierTopicProduct,
        EditSupplierTopic,
        ProductClassifyManage,
        ProductClassifyView,
        ProductRecords,

        //信鸽推送消息
        SendXinGeMessage,

        // 优惠卷使用导出xls
        UserCouponExportXls,

        //价格审核
        HSApprovedPrice,
        //限时抢购活动管理
        CountDownsManager,

        //ios升级
        IosUpgradeList,
        EditIosVersion,

        //Andriod升级
        AndroidUpgradeList,
        EditAndroidVersion,

        //四单申报重发
        ResendHSDocking,
        //四单申报作废
        ValidHSDocking,
        //PO管理
        POManage,
        POAdd,
        POItemAdd,
        POZS,
        POGW,
        POCDList,
        //广告列表
        AdOrderList,

        SMSPromotions,
        //PO申报
        PODeclareAdd,
        //销售报表
        SendOrderSettings,
        //费用管理
        OtherCostSee,
        //费用管理
        OtherCostManage
    }
}
